infoweb/infoweb/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('staff.urls')),
]


if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

infoweb/staff/urls.py
from django.urls import path
from . import views


app_name = 'staff'
urlpatterns = [
    path('', views.index, name='home'),
    path('dashboard/<str:pk>/', views.dashboard, name='dashboard'),
    path('link-account/', views.link_account, name='link_account'),
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login' ),
    path('logout/', views.log_out, name='logout'),
]

infoweb/staff/models.py
from django.db import models
from django.contrib.auth.models import User
from .utils import DEPT, ALL_LGA, GENDER,MARITAL_STATUS,STATES, ID_COLLECTED, GL_and_STEP
# TODO Remember to change null field values to False later i.e 'null=False'


class WorkDetails(models.Model):
    """Work Details for a paticular Staff"""

    class Meta:
        verbose_name_plural = 'Work Details'

    ID_number= models.CharField(max_length=25, primary_key=True, blank=False, unique=True, null=False)
    file_number = models.CharField(max_length=50, unique=True, blank=True, null=True)
    department = models.CharField(choices=(DEPT), max_length=50, null=True, blank=True)
    ID_card= models.CharField(choices=ID_COLLECTED, null=True, blank=True, max_length=5)

    state_directorate=  models.CharField(choices=(STATES), max_length=50, null=True, blank=True) 
    date_of_first_appointment = models.DateField(null=True, blank=True)
    # date_of_present_appointment = models.DateField(null=True, blank=True)
    rank = models.CharField(max_length=50, null=True, blank=True)
    
    
    qualification = models.CharField(max_length=300, null=True, blank=True)
    remarks = models.CharField(max_length=500, null=True, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.ID_number

class PersonalDetails(models.Model):
    """Personal details about a particular Staff"""

    class Meta:
        verbose_name_plural = 'Personal Details'

    work_id_number = models.OneToOneField(WorkDetails, on_delete=models.CASCADE, related_name='personal_detail')
    surname = models.CharField(max_length=250, null=True, blank=True,)
    first_name = models.CharField(max_length=250, null=True, blank=True,)
    
    middle_name = models.CharField(max_length=250, null=True, blank=True,)
    gender = models.CharField(max_length=10, choices=GENDER)
    date_of_birth = models.DateField(null=True, blank=True)
    marital_status = models.CharField(choices=(MARITAL_STATUS), max_length=10, null=True, blank=True)
    
    phone_number = models.CharField(max_length=15, null=True, blank=True)
    state_of_origin = models.CharField(choices=STATES, max_length=50, null=True, blank=True)
    lga =  models.CharField(choices=(ALL_LGA), max_length=50, null=True, blank=True)
    image = models.ImageField(upload_to='upload/', default='profile1.png', null=True, blank=True)
    

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url
    def __str__(self):
        return self.first_name


class LinkedAccount(models.Model):
    """Every User that has been Registered and Linked to an account"""

    class Meta:
        verbose_name_plural = 'Linked Accounts'

    user =models.ForeignKey(User, on_delete=models.CASCADE, related_name='linked_account')

    def __str__(self):
        return str(self.user)
    

infoweb/staff/forms.py
from django.forms import CharField, ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User 
from django import forms

from.models import LinkedAccount, PersonalDetails, WorkDetails


class LinkAccountForm(forms.Form):
    """Form for Linking Users to their Details"""
    id_number = forms.CharField(max_length=200)
    first_name = forms.CharField(max_length=200)

    def save(self, user):
        linked = LinkedAccount.objects.create(user=user)
        linked.save()

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class PersonalDetailsForm(ModelForm):
    class Meta:
        model = PersonalDetails
        fields = '__all__'
        exclude = ['user',]

class WorkDetailsForm(ModelForm):
    class Meta:
        model =WorkDetails
        fields = '__all__'

infoweb/staff/views.py
#* Django imports
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout


from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group        
#====================================================

# My imports
from .models import LinkedAccount, PersonalDetails, WorkDetails
from .forms import LinkAccountForm, PersonalDetails, CreateUserForm
from .decorators import allowed_users, unauthenticated_user

#==============================================================

@unauthenticated_user
def index(request):
  context = {}
  return render(request, 'staff/index.html', context)


#login
@unauthenticated_user
def login_user(request):
  if request.method =='POST':
    username = request.POST.get('username')
    password = request.POST.get('password')
      
    print(username)  
    user = authenticate(request, username=username, password=password)
    print(user)
      
    if user is not None:
      login(request, user)
      print(username, 'logged in')
      return redirect('staff:dashboard', pk=str(request.user.id))
      
    else: messages.error(request, 'Account not Registered')
  
  return render(request, 'staff/login.html')


#Logout
@login_required(login_url='staff:login')
def log_out(request):
  logout(request)
  print(request.user.username, 'logged out')

  return redirect('staff:home')


# Registers a new user
@unauthenticated_user
def register(request):
  form = CreateUserForm()
    
  if request.method=='POST':
    form = CreateUserForm(request.POST)
    if form.is_valid():
      form.save()
      username = form.cleaned_data.get('username')
      
      messages.success(request," Account was Created for "+username)
      return redirect('staff:login')
    else:
      messages.error(request, 'Incorrect credentials')
        
  context = {'form':form}
  
  return render(request,'staff/register.html', context)


@login_required(login_url='staff:login')
def dashboard(request, pk):
  context: dict = {}

  if str(request.user.id) == str(pk):

    try:
      work = WorkDetails.objects.get(user=pk)
      context['work'] = work
      
    except Exception as error:
      print(request.user.id)
      print(f"{error=}")
      return redirect('staff:link_account')

  else:
    print(f'Please Login First, request.user:{request.user}, pk:{pk}')
    return HttpResponse("Please Login First")
  
  return render(request, 'staff/dashboard.html', context)



@login_required(login_url='staff:login')
def link_account(request):
  available_linked_users = [ str(name) for name in LinkedAccount.objects.all()]
  
  if request.method == 'POST':
    print(request.user)

    #Check if account was linked before now to avoid duplicates
    if str(request.user) in available_linked_users:
      return redirect('staff:dashboard', pk=request.user.id)

    else: 
      form = LinkAccountForm(request.POST)
      if form.is_valid():
      
        collected_user_id = form.cleaned_data['id_number']
        collected_first_name = form.cleaned_data['first_name']

        #Check if the data corresponds from the database  
        try:
          work_details = WorkDetails.objects.get(user=request.user)
          ID, FILE = (work_details.ID_number, work_details.personal_detail.first_name,)

        except WorkDetails.DoesNotExist as err:
          print(f"{request.user} does not Exist")

        except AttributeError as err:
          messages.error(request, "such User does not exist")
          print(f"{err=}")

        else:
    
          if (ID==collected_user_id and FILE==collected_first_name):
            form.save(request.user)
            print("\nNew User Added/Linked")
          
            return redirect('staff:dashboard', pk=request.user.id) 
          
          else:
            messages.error(request, "Invalid Credentials !!!")
  

    # if a GET (or any other method) we'll create a blank form
  else:

    #Check if account was linked before now to avoid duplicates
    if str(request.user) in available_linked_users:
      return redirect('staff:dashboard', pk=request.user.id)

    else: 
      form = LinkAccountForm()

  return render(request, 'staff/link_account.html', {'form': form})

infoweb/templates/staff/dashboard.html
    {% extends 'base.html' %}
    {% load static%}
    
    {% block title %}
      <title> {{ request.user.username }} · InfoWeb </title>
    {% endblock title %}
    
    {% block style %}
      <link rel="stylesheet" href="{% static  'js/custom/dashboard.js' %}">
      <link rel="stylesheet" href="{% static  'css/bootstrap/bootstrap.min.css' %}">
      <link rel="stylesheet" href="{% static  'js/bootstrap/bootstrap.min.js' %}">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    <link rel="stylesheet" href="{% static  'js/bootstrap/bootstrap.min.js' %}">
    {% endblock style %}
    
    {% block content %}

<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">InfoWeb</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
      <a class="nav-link px-3" href="{% url 'staff:logout'%}">Sign out</a>
    </div>
  </div>
</header>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">
              <span data-feather="home"></span>
              {% if user.is_authenticated %}
                <img src="{{ work.personal_detail.image.url }}" alt="image" width="15%" height="15%" style="border-radius: 50%;"> {{ user.username|title }}
              {% endif %}
            </a>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Staff Support</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Feedback
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Upload Passport
            </a>
          </li>
          
        </ul>
      </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2"><img src="{{ work.personal_detail.image.url }}" alt="image" width="15%" height="15%" style="border-radius: 50%;">  {{user.username|title}}'s Dashboard</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group me-2">
            <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
          </div>
        </div>
      </div>

      {% block canvas %}
        {% comment %}
          <canvas class="my-4 w-100" id="myChart" width="900" height="38"></canvas>
        {% endcomment %}
      {% endblock canvas %}
      
      <h2>Personal Details</h2>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
              <tr>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">Middle Name</th>
                <th scope="col">Gender</th>
                <th scope="col">Date of Birth</th>
              </tr>
            </thead>
              <tr>        
                  <td>{{ work.personal_detail.first_name }}</td>
                  <td>{{ work.personal_detail.surname }}</td>
                  <td>{{ work.personal_detail.middle_name }}</td>
                  <td>{{ work.personal_detail.gender }}</td>
                  <td>{{ work.personal_detail.date_of_birth }}</td>
              </tr>
              
              <br>

                <thead>
                  <tr>
                    <th scope="col">Phone Number</th>
                    <th scope="col">State of Origin</th>
                    <th scope="col">Local Government Area</th>
                    <th scope="col">Marital Status</th>
                  </tr>
                </thead>
                  <tr>
                    <td>{{ work.personal_detail.phone_number }}</td>
                    <td>{{ work.personal_detail.state_of_origin }}</td>
                    <td>{{ work.personal_detail.lga }}</td>
                    <td>{{ work.personal_detail.marital_status }}</td>
                  </tr>  
              </tr>
      </table>
      </div>

      <br>
      <br>

      <h2>Work Details</h2>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
              <tr>
                <th scope="col">Date of First Appointment</th>
                <th scope="col">Date of Present Appointment</th>
                <th scope="col">Designation/Rank</th>
                <th scope="col">Grade Level/Step</th>
                <th scope="col">State Directorate</th>
              </tr>
            </thead>
              <tr>        
                  <td>{{ work.personal_detail.first_name }}</td>
                  <td>{{ work.personal_detail.surname }}</td>
                  <td>{{ work.personal_detail.middle_name }}</td>
                  <td>{{ work.personal_detail.gender }}</td>
                  <td>{{ work.personal_detail.gender }}</td>
              </tr>
      </table>
    </main>
  </div>
</div>

<script src="{% static  'js/bootstrap/bootstrap.bundle.min.js' %}"></script>
{% endblock content %}

infoweb/templates/staff/index.html
{% extends 'base.html'%}
{% load static %}

   
    {% block title %}
        <title>Home · InfoWeb</title>
    {% endblock title %}

    {% block style %}
        <style>
            .b-example-divider {
                height: 3rem;
                background-color: rgba(0, 0, 0, .1);
                border: solid rgba(0, 0, 0, .15);
                border-width: 1px 0;
                box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
            }

            @media (min-width: 992px) {
            .rounded-lg-3 { border-radius: .3rem; }
            }

        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
            font-size: 3.5rem;
            }
        }

        .infoweb{
          color: rgb(119, 71, 9);
        }
        </style>
    {% endblock style %}

{% block content %}

<script>
  msg = '{{ message }}'
  function pop_up(msg){
    if (msg != 0) {
      alert("You Have Been Logged Out !!")
    }
  }
</script>

  <div class="b-example-divider"></div>

  <div class="container my-5">
    <div class="row p-4 pb-0 pe-lg-0 pt-lg-5 align-items-center rounded-3 border shadow-lg">
      <div class="col-lg-7 p-3 p-lg-5 pt-lg-3">
        <h1 class="display-4 fw-bold lh-1">Welcome to <span class="infoweb">InfoWeb</span></h1>
        <p class="lead"><span class="infoweb">InfoWeb</span> Looks to make Interaction with infoclip  a lot SIMPLER. What will YOU Like to do&quest;</p>
        <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4 mb-lg-3">

          <a href="http://" type="button" class="btn btn-outline-secondary btn-lg px-4" target="_blank" rel="noopener noreferrer">Upload Passport</a>
          <a href="{% url 'staff:login'%}" type="button" class="btn btn-primary btn-lg px-4 me-md-2 fw-bold" target="_blank" rel="noopener noreferrer">Login</a>
          <a href="{% url 'staff:register' %}" type="button" class="btn btn-warning btn-lg px-4" target="_blank" rel="noopener noreferrer">Register</a>

        </div>
      </div>
      <div class="col-lg-4 offset-lg-1 p-0 overflow-hidden shadow-lg">
          <img class="rounded-lg-3" src="{% static 'images/databank2.jpeg'%}" alt="" width="100%" height="100%">
      </div>
    </div>
  </div>

  <div class="b-example-divider"></div>
{% endblock content %}

infoweb/templates/staff/link_account.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Link Account · InfoWeb</title>
{% endblock title %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/custom/login_style.css'%}" />

<style>
  .msg {
    text-align: center;
  }
</style>
{% endblock style %}

{% block content%}
<div class="container h-100">
  <div class="d-flex justify-content-center h-100">
    <div class="user_card">
      <div class="d-flex justify-content-center">
        <h3 id="form-title">LINK ACCOUNT</h3>
      </div>

      <div class="d-flex justify-content-center form_container">
        <form method="POST">
          {% csrf_token %}
          
          {% comment %}
          <!-- TODO: Handle with signals later -->
          <!-- TODO: Change user to first name and last name-->
          {% endcomment %}
          <div class="input-group mb-2">{{form.id_number}}</div>

          <div class="input-group mb-2">{{form.first_name}}</div>

          <div class="d-flex justify-content-center mt-3 login_container">
            <input class="btn login_btn" type="submit" value="Link Account" />
          </div>
        </form>
      </div>
      <span class="msg"> {% for msg in messages%}{{ msg }}{% endfor %}</span>
    </div>
  </div>
</div>

<script>
	
  var form_fields = document.getElementsByTagName("input");
  form_fields[1].placeholder = "ID: eg. new_id";
  form_fields[2].placeholder = "First Name: eg. Nick";

  for (var field in form_fields) {
    form_fields[field].className += " form-control";
  }
</script>

{% endblock content%}

infoweb/templates/staff/login.html
{% extends 'base.html' %}
{% load static%}

{% block title %}
	<title> Login · InfoWeb </title>
{% endblock title %}

{% block style %}
	<link rel="stylesheet" href="{% static 'css/custom/login_style.css'%}"/>
{% endblock style %}

{% block content %}
<div class="container h-100">
  <div class="d-flex justify-content-center h-100">
    <div class="user_card">
      <div class="d-flex justify-content-center">
        <h3 id="form-title">LOGIN</h3>
      </div>
      <div class="d-flex justify-content-center form_container">
        <form method="POST" action="">
          {% csrf_token %}
          <div class="input-group mb-3">
            <input type="text" name="username" id="username" />
          </div>

          <div class="input-group mb-2">
            <input type="password" name="password" id="password" />
          </div>

          {% for msg in messages%}
            {% if msg is True %}
            <span></span>

            {% else %}
            <p style="text-align: center">{{ msg }} </p>
            {% endif%}
          {% endfor %}
          <div class="d-flex justify-content-center mt-3 login_container">
            <input
              onclick="validateForm()"
              class="btn login_btn"
              type="submit"
              value="Login"
            />
          </div>
        </form>
      </div>

      <div class="mt-4">
        <div class="d-flex justify-content-center links">
          <a href="#" class="ml-2">Forgot Password&quest;</a>
        </div>

        <div class="d-flex justify-content-center links">
          New Here&quest;
          <a href="{% url 'staff:register' %}" class="ml-2">Register</a>
        </div>
      </div>
    </div>
  </div>
</div>

<script src="{% static 'js/custom/validate_login.js' %}"></script>

<script>
  var form_fields = document.getElementsByTagName("input");
  form_fields[1].placeholder = "Username..";
  form_fields[2].placeholder = "Enter password...";

  for (var field in form_fields) {
    form_fields[field].className += " form-control";
  }
</script>
{% endblock content %}

infoweb/templates/staff/register.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <title>Register</title>
    <link
      rel="stylesheet"
      href="{% static 'css/bootstrap/bootstrap.min.css'%}"
    />
    <link rel="stylesheet" href="{% static 'css/custom/login_style.css'%}" />
    <link
      rel="apple-touch-icon"
      sizes="180x180"
      href="{% static 'fav/apple-touch-icon.png' %}"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href="{% static 'fav/favicon-32x32.png' %}"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href="{% static 'fav/favicon-16x16.png' %}"
    />
    <style>
      .msg {
        text-align: center;
      }
    </style>
  </head>

  <body>
    <div class="container h-100">
      <div class="d-flex justify-content-center h-100">
        <div class="user_card">
          <div class="d-flex justify-content-center">
            <h3 id="form-title">REGISTER ACCOUNT</h3>
          </div>

          <div class="d-flex justify-content-center form_container">
            <form method="POST">
              {% csrf_token %}

              <div class="input-group mb-2">{{ form.username }}</div>

              <div class="input-group mb-2">{{form.email}}</div>

              <div class="input-group mb-2">{{form.password1}}</div>

              <div class="input-group mb-2">{{form.password2}}</div>

              <div class="d-flex justify-content-center mt-3 login_container">
                <input
                  onclick="validateForm()"
                  class="btn login_btn"
                  type="submit"
                  value="Register Account"
                />
              </div>
            </form>
          </div>
          <span class="msg">
            {% for msg in messages%}{{ msg }}{% endfor %}</span
          >

          <div class="mt-4">
            <div class="d-flex justify-content-center links">
              Already have an account?
              <a href="{% url 'staff:login'%}" class="ml-2">Login</a>
            </div>
          </div>
        </div>
      </div>
    </div>

    <script src="{% static 'js/custom/validate_registration.js' %}"></script>

    <script>
      var form_fields = document.getElementsByTagName("input");
      form_fields[1].placeholder = "Username..";
      form_fields[2].placeholder = "Email..";
      form_fields[3].placeholder = "Enter password...";
      form_fields[4].placeholder = "Re-enter Password...";

      for (var field in form_fields) {
        form_fields[field].className += " form-control";
      }
    </script>
  </body>
</html>